name: Evaluate Flake
on: 
  pull_request:
    branches: ["*"]
  push:
    branches: ["*"]
jobs:
  check:
    name: format check
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flake-checker-action@main
