name: Lint
on:
  pull_request:
    branches: ["*"]
    paths-ignore:
      - '**/*.md'
  push:
    branches: ["main", "dev"]
    paths-ignore:
      - '**/*.md'

jobs:
  statix:
    name: Statix Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v12
        with:
          name: statix
      - uses: jocelynthode/statix-action@master
