name: Sync changes to remote child branches

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    types: [ closed ]
    paths-ignore:
      - 'dae/metadata.json'
      - 'daed/metadata.json'

env:
  PR_TEAM_REVIEWERS: |
    nix

jobs:
  sync-changes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        include:
          - branch: unstable
            labels: branch/unstable
          - branch: experiment
            labels: branch/experiment
      fail-fast: false
    steps:
      - uses: actions/checkout@main
        with:
          ref: ${{ github.event.repository.default_branch }}
          fetch-depth: 0

      - name: Cherry pick changes into target branch
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
        with:
          branch: ${{ matrix.branch }}
          labels: |
            git/cherry-pick
            ${{ matrix.labels }}
          team-reviewers: ${{ env.PR_TEAM_REVIEWERS }}
          title: '[cherry-pick] {old_title}'
          body: 'ci: cherry picking #{old_pull_request_id} onto ${{ matrix.branch }}'

