on:
  pull_request:
  push:
    branches: [main, exp]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    concurrency: build-${{matrix.jobs.branch}}-${{matrix.jobs.target}}
    steps:
    - uses: actions/checkout@v4
    - name: setup-nix
      uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-conf: |
          extra-substituters = https://daeuniverse.cachix.org
          extra-trusted-public-keys = daeuniverse.cachix.org-1:8hRIzkQmAKxeuYY3c/W1I7QbZimYphiPX/E7epYNTeM=
    - name: build
      env:
        CACHIX_AUTH_TOKEN: "${{ secrets.cachix_auth_token }}"
      run: nix develop -c ./main.nu build
